# Japanese translations for Cabot-test package.
# Copyright (C) 2022 ORGANIZATION
# Automatically generated, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: Cabot-test 7\n"
"POT-Creation-Date: 2022-04-05 19:36+0900\n"
"PO-Revision-Date: 2022-04-05 10:17+0900\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: CaBot-odrive-diag.py:80 CaBot-odrive-diag.py:81
msgid "ODrivetool:not_found_find_any:"
msgstr "ODriveがodrivetoolで見つかりません。"

#: CaBot-odrive-diag.py:85 CaBot-odrive-diag.py:87
msgid "ODrivetool:found_find_any:serial_no:"
msgstr "ODriveは接続されています。シリアル番号：　"

#: CaBot-odrive-diag.py:89 CaBot-odrive-diag.py:91
msgid "ODrivetool:have_err:NumOfErr:"
msgstr "ODriveでエラーが報告されていました。エラー数：　"

#: CaBot-odrive-diag.py:96 CaBot-odrive-diag.py:98
msgid "ODrivetool:TimeoutError:"
msgstr "ODriveがodrivetoolで見つかりません。（タイムアウト）"

#: CaBot-odrive-diag.py:102 CaBot-odrive-diag.py:104
msgid "ODrivetool:Exception:"
msgstr "ODriveの検索中に、エラーが発生しました。"
